### ISSUE TITLE
Download button doesn't work due to CSP

### ISSUE THREAD

**Issue by tflidd** [nextcloud/files_pdfviewer#10]
The download button in the pdf_viewer app doesn't work in Firefox (Safari probably as well). It was already reported here: https://github.com/owncloud/files_pdfviewer/issues/119

**Comment by nickvergessen** [comment]
@LukasReschke

**Comment by trockenasche** [comment]
I'm not sure about it, but it works for me
[https://github.com/trockenasche/server/commit/3736fb53b6eef49b9712d873ec02a35c40f2c54e](https://github.com/trockenasche/server/commit/3736fb53b6eef49b9712d873ec02a35c40f2c54e)

**Comment by nickvergessen** [comment]
I tried https://github.com/owncloud/files_pdfviewer/pull/131/files but obviously this does not help.

I made the fix from @trockenasche at https://github.com/nextcloud/server/blob/b70b138bdb6c59df8c94cb973155d7ab4a41113b/apps/files/lib/Controller/ViewController.php#L216-L216
```php
$policy->addAllowedFrameDomain('blob:');
```

That fixed it. But not sure if that has other implications.

**Comment by TheMrApostel** [comment]
I would like to report that the issue still exists with safari.
Firefox and so on are working like a charme.
On the users iphone / ipad the download button is broken.
The fix was also applied but doesn't changed the behaviour.

I am using Nextcloud 11.0.4
Can we open this issue or should i create a new one?
