### ISSUE TITLE
The little cross that is supposed to close the pdf does nothing

### ISSUE THREAD

**Issue by elpraga** [nextcloud/files_pdfviewer#242]
I've noticed this behavior since upgrading to NC 20.0.0

Before that, it used to close the document as it is supposed to.

**Comment by skjnldsv** [comment]
Which one are we talking about, could you add screenshot? :)

**Comment by skjnldsv** [comment]
Right, it appeared again
![Uploading Capture d’écran_2020-10-11_01-06-23.png…]()

**Comment by bes1002t** [comment]
why should the close button be removed instead of let it close the pdf? how is the user closing the viewer afterwards?

**Comment by skjnldsv** [comment]
@bes1002t from the Viewer closing button

**Comment by bes1002t** [comment]
@skjnldsv thanks for that info. When is this included into pdf viewer? because 1.8.0 still looks like the common pdf viewer, with the common x button which is working, but the button is very tiny.

![pdf_viewer](https://user-images.githubusercontent.com/3890580/96637271-c03b7200-131e-11eb-9e51-a94cb580a3fc.png)

**Comment by skjnldsv** [comment]
> @skjnldsv thanks for that info. When is this included into pdf viewer? because 1.8.0 still looks like the common pdf viewer, with the common x button which is working, but the button is very tiny.

From nextcloud 20 and above :)
