### ISSUE TITLE
Add localisation

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/files_pdfviewer#831]
Please, add the localisation of the PDF Viewer app. Here is the zip archive with all necessary files, including 
`tempales/viewer.php` updated with localisation tags
`l10n/uk.js`
`l10n/uk.json` strings for the Ukrainian localisation
`l10n/en_GB.js`
`l10n/en_GB.json` strings for the Brittish English localisation
[localisation.zip](https://github.com/nextcloud/files_pdfviewer/files/12841082/localisation.zip)

Would that be possible to create the template and add it as a transifex pool, as well?

**Comment by danxuliu** [comment]
Thanks for the translations!

Unfortunately, as explained in https://github.com/nextcloud/files_pdfviewer/pull/826#pullrequestreview-1664233442 the translations are already available in PDF.js, and the reason why they are not shown is that the language is got from the browser preferences rather than the Nextcloud settings ([which is a bug that should be fixed](https://github.com/nextcloud/files_pdfviewer/issues/834)).

**Comment by ostasevych** [comment]
> Thanks for the translations!
> 
> Unfortunately, as explained in [#826 (review)](https://github.com/nextcloud/files_pdfviewer/pull/826#pullrequestreview-1664233442) the translations are already available in PDF.js, and the reason why they are not shown is that the language is got from the browser preferences rather than the Nextcloud settings ([which is a bug that should be fixed](https://github.com/nextcloud/files_pdfviewer/issues/834)).

Thank you for your comment. As I've added in that issue, my suggestion is to follow the common rules of placing translation files in the proper folders, thus, creating translation templates, as well as to use Transifex. All other approaches are confusing devs...

**Comment by ostasevych** [comment]
Please, reopen this issue, as it is not solved.
