### ISSUE TITLE
Localisation is not working properly.

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/files_pdfviewer#834]
Despite of having the translation of PDF.js in other than English language, and selected by user non-English localisation the UI is shown only in English. Tested with the Ukrainian localisation.

In order the UI is shown in Ukrainian I have added l-tags to the viewer.php and created l10n/uk.json file with translations.

Please, re-check it again.

Ref: reopened bug https://github.com/nextcloud/files_pdfviewer/pull/826

## How to test

- In the browser preferences, set the preferred language to open pages to something other than English
- In personal Nextcloud settings, set your preferred language to a different language than the one in the browser
- Open the PDF viewer

### Expected result

The UI messages are shown in the same language set in Nextcloud settings

### Actual result

The UI messages are shown in the same language set in browser preferences

**Comment by danxuliu** [comment]
The problem is that the language is got from the browser preferences (the default PDF.js behaviour) instead of from the Nextcloud settings.

It would be necessary to force PDF.js to use a specific language rather than auto-detecting it from the browser preferences. Unfortunately I have not been able to figure out how yet; I expected it to be just a matter of adding [DFViewerApplicationOptions.set('disablePreferences', {LOCALE_CODE})](https://github.com/mozilla/pdf.js/blob/v3.9.179/web/app.js#L397) (where {LOCALE_CODE} would be the same set in Nextcloud settings) when [the app is initialized](https://github.com/nextcloud/files_pdfviewer/blob/7a9f7cfcbc93ef65b1ae73d6f72482cd4fd72719/src/workersrc.js#L39-L48), but that does not seem to work :-(

**Comment by ostasevych** [comment]
> The problem is that the language is got from the browser preferences (the default PDF.js behaviour) instead of from the Nextcloud settings.
> 
> It would be necessary to force PDF.js to use a specific language rather than auto-detecting it from the browser preferences. Unfortunately I have not been able to figure out how yet; I expected it to be just a matter of adding [DFViewerApplicationOptions.set('disablePreferences', {LOCALE_CODE})](https://github.com/mozilla/pdf.js/blob/v3.9.179/web/app.js#L397) (where {LOCALE_CODE} would be the same set in Nextcloud settings) when [the app is initialized](https://github.com/nextcloud/files_pdfviewer/blob/7a9f7cfcbc93ef65b1ae73d6f72482cd4fd72719/src/workersrc.js#L39-L48), but that does not seem to work :-(

In my opinion it is always good to have universal approach to the localisation. Moreover, it will be good to have it placed in Transifex.

**Comment by danxuliu** [comment]
While I agree that having a common translation system for all Nextcloud apps is good the problem I see in this case is that it would duplicate efforts due to having to translate again in Nextcloud strings that were already translated in PDF.js.

But I am not a translator, so... @rakekniven May I ask your view on this? :-) You can find the context in this issue and in https://github.com/nextcloud/files_pdfviewer/pull/826. Thanks a lot!

And besides the duplicated effort that change would make more difficult to merge changes from PDF.js to _templates/viewer.php_ when updating to a new PDF.js version (it would be still possible, of course, it is simply that it would be more difficult and time consuming, as any HTML element with a visible string would be different from the original file from PDF.js).

**Comment by ostasevych** [comment]
> While I agree that having a common translation system for all Nextcloud apps is good the problem I see in this case is that it would duplicate efforts due to having to translate again in Nextcloud strings that were already translated in PDF.js.
> 
> But I am not a translator, so... @rakekniven May I ask your view on this? :-) You can find the context in this issue and in #826. Thanks a lot!
> 
> And besides the duplicated effort that change would make more difficult to merge changes from PDF.js to _templates/viewer.php_ when updating to a new PDF.js version (it would be still possible, of course, it is simply that it would be more difficult and time consuming, as any HTML element with a visible string would be different from the original file from PDF.js).

Thanks for supporting my idea. Mostly, it has been already done by me in this commit https://github.com/nextcloud/files_pdfviewer/pull/826/commits/761469d0f286f463857dcf74f82a9fc0405e28a2

**Comment by ostasevych** [comment]
Again, no localisation in 28.0.10. The language is still English.

**Comment by susnux** [comment]
> Same issue with NC 29.0.7 (French local)

I can not reproduce this, my browser language is German and if I set my Nextcloud language to French it works (Fench UI is shown):

https://github.com/user-attachments/assets/60d80e7f-b283-42ea-83a9-528bfd927497

**Comment by susnux** [comment]
> An idea to solve this ?
> I am on Nextcloud AIO v9.6.0 (NC 29.0.7)

I tested it with default deployment via ZIP file, there it works. So maybe a AiO deployment issue (webserver not serving it correctly).
Maybe open a ticket over there?
