### ISSUE TITLE
PDF-viewer not full-screen anymore on NC28

### ISSUE THREAD

**Issue by szaimen** [nextcloud/files_pdfviewer#843]
@danxuliu I tested this and it works fine generally but I don't know why and if it is caused by this PR but somehow the pdf viewer has two scrollbars now:
![image](https://github.com/nextcloud/files_pdfviewer/assets/42591237/ec8d3612-b893-4bad-b1c8-caa4bcbabf0a)

Reproduced on NC28

_Originally posted by @szaimen in https://github.com/nextcloud/files_pdfviewer/pull/787#pullrequestreview-1684701363_

**Comment by danxuliu** [comment]
Strangely enough I have not been able to reproduce the double scroll bar issue, but it should be caused by the same change that made the PDF viewer to no longer be shown in full screen. Maybe it depends on the PDF file, I do not know :shrug: 

In any case, the problem is that, although the viewer is "framed" and [leaves a small space at the bottom](https://github.com/nextcloud/viewer/blob/1167195376d7bc91ca2f15fe552a2cf2bcca2998/src/views/Viewer.vue#L1217-L1219), the iframe of the PDF viewer overflows it and uses [the full height of the viewer (leaving a margin at the top for the header)](https://github.com/nextcloud/files_pdfviewer/blob/ef2f09c40bf3f367dac2d1f13a06087ba810793b/src/views/PDFView.vue#L177-L178). However, in Nextcloud 28, [NcModal sets `overflow: auto` to its content](https://github.com/nextcloud-libraries/nextcloud-vue/commit/694bd99fb5cc53bd28cf209e39ed54e2e9981942#diff-21d5415d2bb4608c84b6f25060e51a51df2703f51927d007868a8d540b4d6d2aR934), so the PDF viewer is now [clipped at the bottom and no longer overflows (but shows a scroll bar)](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow#auto).

Note that [`overflow: auto` has been set already in the NcModal container for several versions](https://github.com/nextcloud-libraries/nextcloud-vue/commit/b8a64f9ac54d80c7c5997c71b44a95a75c76f299#diff-907877e92ada6bf9340562928a4046f5a937f4985041a4f2e3981313538f8f5dR713) before adding the content element and moving the rule to it, and the PDF viewer was working fine. The reason is that the viewer overrides the property with [`overflow: visible` for the NcModal container and the content of the viewer](https://github.com/nextcloud/viewer/blob/1167195376d7bc91ca2f15fe552a2cf2bcca2998/src/views/Viewer.vue#L1203-L1205). However, as `overflow: auto` is now set in the NcModal content, which is [an intermediate element between the NcModal container and the viewer content](https://github.com/nextcloud-libraries/nextcloud-vue/commit/694bd99fb5cc53bd28cf209e39ed54e2e9981942#diff-21d5415d2bb4608c84b6f25060e51a51df2703f51927d007868a8d540b4d6d2aR284-R287), the PDF viewer ends clipped, as `.viewer__content` is already clipped by `.modal-container__content`:
```
<div class="modal-container".../> <!-- "overflow: visible !important" from Viewer.vue -->
  <div class="modal-container__content".../> <!-- "overflow: auto" from NcModal.vue -->
    <div class="viewer__content".../> <!-- "overflow: visible !important" from Viewer.vue -->
```

Setting `overflow: visible !important` for `.modal-container__content` in PDFView.vue is not possible as far as I know, as the component is loaded inside the content itself, and therefore it can not modify the rules of the parent element (but I might be wrong, my Vue-fu is quite rusty :-) ). However, I do not know if overriding that in the viewer itself like done for the others would be a good idea, as that change was introduced [to ensure that the close button of the modal is visible even if the content is scrolled](https://github.com/nextcloud-libraries/nextcloud-vue/pull/4350), and if the overflow is visible I guess that could bring back the issue. On the other hand, that would happen only in the viewer, other modals would not be affected, and maybe it could be required that viewer handlers are responsible to handle the scrolling to ensure that it only affects its own content. Or maybe there is another solution that I am missing, of course :-)

**Comment by szaimen** [comment]
Adjusted https://github.com/nextcloud/files_pdfviewer/pull/845. Should work now without any viewer fix :)
